app_repo: "{{ lookup('env', 'GIT_REPO_URL') | default('https://github.com/jaanu2003/devops-project.git', true) }}"
app_branch: "{{ lookup('env', 'APP_DEPLOY_BRANCH') | default('main', true) }}"
app_dest: /home/ubuntu/devops-project
container_name: flask-container
image_name: devops-flask-app
app_port: 5000
